name: Spik4lite
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - pip
  - pytorch=2.5.0
  - torchvision=0.20.0
  - pytorch-cuda=12.4
  - cuda-version=12.4
  - numpy=2.0.1
  - pyyaml=6.0.2
  - pillow=11.1.0
  - matplotlib=3.10.1
  - cupy=13.4.1
  - torchinfo=1.8.0
  - scipy=1.15.2
  - tqdm=4.67.1
  - packaging=24.2
  - pip:
      - spikingjelly==0.0.0.0.14
      - timm==0.6.12
      - progress==1.6.1
      - tensorboard==2.19.0
      - wandb==0.19.8
